export const DEFINI_MONTANT_FORFAIT = "DEFINI_MONTANT_FORFAIT";
export const CALCUL_OPTION_A = "CALCUL_OPTION_A";
export const UPDATE_ATTRIBUT = "UPDATE_ATTRIBUT";
export const UPDATE_ATTRIBUT_CLIENT = "UPDATE_ATTRIBUT_CLIENT";
export const DEFINETIME = "DEFINETIME";
export const DEFINEREF = "DEFINEREF";





