export const DEFINI_MONTANT_FORFAIT = "DEFINI_MONTANT_FORFAIT";
export const CALCUL_OPTION = "CALCUL_OPTION";
export const CALCUL_OPTION_A = "CALCUL_OPTION_A";
export const UPDATE_ATTRIBUT = "UPDATE_ATTRIBUT";
export const UPDATE_ATTRIBUT_CLIENT = "UPDATE_ATTRIBUT_CLIENT";
export const DEFINETIME = "DEFINETIME";
export const DEFINEREF = "DEFINEREF";
export const ADD_UPDATE_LINE = "ADD_UPDATE_LINE";
export const UPDATE_ATTRIBUT_SA = "UPDATE_ATTRIBUT_SA";
export const UPDATE_TOT_COST = "UPDATE_TOT_COST";








